/**
 * orchestrator.js — GitOps Orchestrator
 *
 * Full pipeline:
 *   1. Capture "after" screenshots via Playwright
 *   2. Diff them against the "before" baseline
 *   3. If changes detected → branch, commit, open GitHub PR with inline screenshots
 *
 * Usage:
 *   npm run qa:run
 *   node src/orchestrator.js
 */

require("dotenv").config();
const shell  = require("shelljs");
const path   = require("path");
const fs     = require("fs");
const { captureAll } = require("../flows/web/capture");
const { diffAll }    = require("./differ");
const { timestamp, DIRS, ROOT, checkForUpdates } = require("./utils");

// ── Config ─────────────────────────────────────────────────────────────────────

const GITHUB_REPO  = process.env.GITHUB_REPO  || "";   // e.g. "your-org/your-repo"
const BASE_BRANCH  = process.env.BASE_BRANCH  || "main";
const PR_LABEL     = process.env.PR_LABEL     || "visual-regression";

// ── Helpers ───────────────────────────────────────────────────────────────────

function run(cmd, opts = {}) {
  const result = shell.exec(cmd, { silent: true, ...opts });
  if (result.code !== 0 && !opts.allowFail) {
    console.error(`\n  ✖  Command failed: ${cmd}`);
    console.error(`     ${result.stderr.trim()}`);
  }
  return result;
}

/** Relative path from repo root, Unix-style — safe for GitHub Markdown. */
function repoRelative(absPath) {
  return path.relative(ROOT, absPath).replace(/\\/g, "/");
}

/**
 * Build the PR body markdown with side-by-side before/after/diff tables.
 */
function buildPRBody(changedResults) {
  const ts = new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC";
  const rows = changedResults.map((r) => {
    const before = r.beforePath ? `![before](${repoRelative(r.beforePath)})` : "_no baseline_";
    const after  = `![after](${repoRelative(r.afterPath)})`;
    const diff   = r.mismatch > 0 ? `![diff](${repoRelative(r.diffPath)})` : "–";
    return `| \`${r.name}\` | ${r.mismatch.toLocaleString()} px | ${before} | ${after} | ${diff} |`;
  });

  return `## 🔬 Visual Regression Report

> Generated by **Spectral Cyclops** · ${ts}

| Screen | Δ Pixels | Before | After | Diff |
|--------|----------|--------|-------|------|
${rows.join("\n")}

---
_Merge this PR to accept the new visual baseline._`;
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function run_pipeline() {
  console.log("\n🕵️  Spectral Cyclops — Full Pipeline\n");

  // Check for updates (silent background, 3s delay)
  setTimeout(checkForUpdates, 3000);

  // 1. Capture
  console.log("Phase 1 — Capture\n");
  const captureResults = await captureAll("after");
  const captured = captureResults.filter((r) => r.ok);
  if (captured.length === 0) {
    console.error("\n  ✖  No screenshots captured. Aborting.\n");
    process.exit(1);
  }

  // 2. Diff
  console.log("\nPhase 2 — Diff\n");
  const diffResults = diffAll();
  const changed = diffResults.filter((r) => !r.skipped && r.mismatch > 0);

  if (changed.length === 0) {
    console.log("\n  ✅  No visual changes detected. Nothing to push.\n");
    process.exit(0);
  }

  console.log(`\n  🔴  ${changed.length} screen(s) changed.\n`);

  // 3. GitOps
  console.log("Phase 3 — GitOps\n");

  const branchName = `visual-qa/${timestamp()}`;

  // Ensure we're on a clean state before branching
  run(`git checkout ${BASE_BRANCH}`, { allowFail: true });
  run(`git pull origin ${BASE_BRANCH}`, { allowFail: true });
  run(`git checkout -b ${branchName}`);

  // Stage screenshots
  const filesToAdd = [
    ...changed.map((r) => repoRelative(r.afterPath)),
    ...changed.filter((r) => r.mismatch > 0).map((r) => repoRelative(r.diffPath)),
  ].filter(Boolean);

  run(`git add ${filesToAdd.map((f) => `"${f}"`).join(" ")}`);

  const summary = changed.map((r) => `${r.name} (${r.mismatch.toLocaleString()} px)`).join(", ");
  run(`git commit -m "chore(visual-qa): capture changes — ${summary}"`);

  run(`git push origin ${branchName}`);

  // 4. Open PR
  console.log("\nPhase 4 — Pull Request\n");
  const body = buildPRBody(changed);
  const bodyFile = path.join(ROOT, ".spectral_pr_body.md");
  fs.writeFileSync(bodyFile, body);

  const repoFlag = GITHUB_REPO ? `--repo ${GITHUB_REPO}` : "";
  const labelFlag = PR_LABEL ? `--label "${PR_LABEL}"` : "";

  const pr = run(
    `gh pr create --title "👁 Visual changes: ${changed.map((r) => r.name).join(", ")}" ` +
    `--body-file "${bodyFile}" --base ${BASE_BRANCH} ${repoFlag} ${labelFlag}`,
    { allowFail: true }
  );

  fs.unlinkSync(bodyFile);

  if (pr.code === 0) {
    console.log(`\n  ✅  PR opened:\n     ${pr.stdout.trim()}\n`);
  } else {
    console.log(`\n  ⚠  Could not open PR via gh CLI. Branch pushed: ${branchName}`);
    console.log(`     Open it manually or set GITHUB_REPO in your .env\n`);
  }
}

run_pipeline().catch((err) => {
  console.error("\n  ✖  Pipeline error:", err.message);
  process.exit(1);
});
